-- tutor
ALTER TABLE tutor
DROP COLUMN ADRESS;
ALTER TABLE tutor
DROP COLUMN POSTLZ;
ALTER TABLE tutor
DROP COLUMN WHNORT;
ALTER TABLE tutor
DROP COLUMN ARIDFA;
ALTER TABLE tutor
DROP COLUMN NAHIOR;
ALTER TABLE tutor
DROP COLUMN ARIDMO;

-- student
ALTER TABLE student
DROP COLUMN ADRESS;
ALTER TABLE student
DROP COLUMN POSTLZ;
ALTER TABLE student
DROP COLUMN WHNORT;
ALTER TABLE student
DROP COLUMN ARIDFA;

-- manager
ALTER TABLE manager
DROP COLUMN ADRESS;
ALTER TABLE manager
DROP COLUMN POSTLZ;
ALTER TABLE manager
DROP COLUMN WHNORT;
ALTER TABLE manager
DROP COLUMN ACAUSW;
